/**
 * Created by ira on 24.02.16.
 */

const Constants = {
  /*  USER_SIGNED_IN: 'USER_SIGNED_IN',
   CURRENT_USER: 'CURRENT_USER',
   USER_SIGNED_OUT: 'USER_SIGNED_OUT',*/
  LOAD_TASKS: 'LOAD_TASKS',
  LOAD_TASKS_SUCCESS: 'LOAD_TASKS_SUCCESS',
  LOAD_TASKS_FAIL: 'LOAD_TASKS_FAIL',
  EDIT_TASK_START: 'EDIT_TASK_START',
  EDIT_TASK_STOP: 'EDIT_TASK_STOP',
  SAVE_TASK: 'SAVE_TASK',
  SAVE_TASK_SUCCESS: 'SAVE_TASK_SUCCESS',
  SAVE_TASK_FAIL: 'SAVE_TASK_FAIL',

  TASKS_FETCHING: 'TASKS_FETCHING',

  FETHING_CURRENT_TASK: 'FETHING_CURRENT_TASK',
  SET_CURRENT_TASK: 'SET_CURRENT_TASK'

};

export default Constants;
