/**
 * Created by ira on 24.02.16.
 */

const Constants = {
  /*  USER_SIGNED_IN: 'USER_SIGNED_IN',
   CURRENT_USER: 'CURRENT_USER',
   USER_SIGNED_OUT: 'USER_SIGNED_OUT',*/
  LOAD_TASKS: 'LOAD_TASKS',
  LOAD_TASKS_SUCCESS: 'LOAD_TASKS_SUCCESS',
  LOAD_TASKS_FAIL: 'LOAD_TASKS_FAIL',
  EDIT_TASK_START: 'EDIT_TASK_START',
  EDIT_TASK_STOP: 'EDIT_TASK_STOP',
  SAVE_TASK: 'SAVE_TASK',
  SAVE_TASK_SUCCESS: 'SAVE_TASK_SUCCESS',
  SAVE_TASK_FAIL: 'SAVE_TASK_FAIL',
  SET_TASKS_SEARCH_STRING: 'SET_TASKS_SEARCH_STRING',
  SET_TASKS_FILTER_FIELD: 'SET_TASKS_FILTER_FIELD',
  TOGGLE_TASKS_SORT_ORDER: 'TOGGLE_TASKS_SORT_ORDER',
  TOGGLE_TASKS_GROUPS: 'TOGGLE_TASKS_GROUPS',

  TASKS_FETCHING: 'TASKS_FETCHING',

  LOAD_CURRENT_TASK: 'LOAD_CURRENT_TASK',
  LOAD_CURRENT_TASK_SUCCESS: 'LOAD_CURRENT_TASK_SUCCESS',
  LOAD_CURRENT_TASK_FAIL: 'LOAD_CURRENT_TASK_FAIL'

};

export default Constants;
