/**
 * Created by ira on 24.02.16.
 */

const Constants = {
  /*  USER_SIGNED_IN: 'USER_SIGNED_IN',
   CURRENT_USER: 'CURRENT_USER',
   USER_SIGNED_OUT: 'USER_SIGNED_OUT',*/
  LOAD_TASKS: 'LOAD_TASKS',
  LOAD_TASKS_SUCCESS: 'LOAD_TASKS_SUCCESS',
  LOAD_TASKS_FAIL: 'LOAD_TASKS_FAIL',
  EDIT_TASK_START: 'EDIT_TASK_START',
  EDIT_TASK_STOP: 'EDIT_TASK_STOP',
  SAVE_TASK: 'SAVE_TASK',
  SAVE_TASK_SUCCESS: 'SAVE_TASK_SUCCESS',
  SAVE_TASK_FAIL: 'SAVE_TASK_FAIL',
  SET_TASKS_SEARCH_STRING: 'SET_TASKS_SEARCH_STRING',
  SET_TASKS_FILTER_FIELD: 'SET_TASKS_FILTER_FIELD',
  TOGGLE_TASKS_SORT_ORDER: 'TOGGLE_TASKS_SORT_ORDER',
  TOGGLE_TASKS_GROUPS: 'TOGGLE_TASKS_GROUPS',
  TOGGLE_TASKS_TABLE_LAYOUT: 'TOGGLE_TASKS_TABLE_LAYOUT',

  TASKS_FETCHING: 'TASKS_FETCHING',

  LOAD_CURRENT_TASK: 'LOAD_CURRENT_TASK',
  LOAD_CURRENT_TASK_SUCCESS: 'LOAD_CURRENT_TASK_SUCCESS',
  LOAD_CURRENT_TASK_FAIL: 'LOAD_CURRENT_TASK_FAIL',
  SET_CURRENT_TASK_PRIORITY: 'SET_CURRENT_TASK_PRIORITY',
  SET_CURRENT_TYPE_TASK: 'SET_CURRENT_TYPE_TASK',
  SET_CURRENT_TASK_STATUS: 'SET_CURRENT_TASK_STATUS',

  // auth
  LOAD: 'redux-example/auth/LOAD',
  LOAD_SUCCESS: 'redux-example/auth/LOAD_SUCCESS',
  LOAD_FAIL: 'redux-example/auth/LOAD_FAIL',
  LOGIN: 'redux-example/auth/LOGIN',
  LOGIN_SUCCESS: 'redux-example/auth/LOGIN_SUCCESS',
  LOGIN_FAIL: 'redux-example/auth/LOGIN_FAIL',
  LOGOUT: 'redux-example/auth/LOGOUT',
  LOGOUT_SUCCESS: 'redux-example/auth/LOGOUT_SUCCESS',
  LOGOUT_FAIL: 'redux-example/auth/LOGOUT_FAIL',
};

export default Constants;
