export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_RECEIVED = 'AUTHENTICATION_RECEIVED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_RECEIVED = 'LOGOUT_RECEIVED';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';
