export const AUTHENTICATION_START = 'AUTHENTICATION_START';
export const AUTHENTICATION_RECEIVED = 'AUTHENTICATION_RECEIVED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const USER_INFO_RECEIVE_START = 'USER_INFO_RECEIVE_START';
export const USER_INFO_RECEIVE_SUCCESS = 'USER_INFO_RECEIVE_SUCCESS';
export const USER_INFO_RECEIVE_ERROR = 'USER_INFO_RECEIVE_ERROR';
