export const GET_EXTERNAL_USERS_START = 'GET_EXTERNAL_USERS_START';
export const GET_EXTERNAL_USERS_SUCCESS = 'GET_EXTERNAL_USERS_SUCCESS';
export const EDIT_EXTERNAL_USER_START = 'EDIT_EXTERNAL_USER_START';
export const EDIT_EXTERNAL_USER_SUCCESS = 'EDIT_EXTERNAL_USER_SUCCESS';
export const ADD_EXTERNAL_USER_START = 'ADD_EXTERNAL_USER_START';
export const ADD_EXTERNAL_USER_SUCCESS = 'ADD_EXTERNAL_USER_SUCCESS';
