export const PROJECT_INFO_RECEIVE_START = 'PROJECT_INFO_RECEIVE_START';
export const PROJECT_INFO_RECEIVE_SUCCESS = 'PROJECT_INFO_RECEIVE_SUCCESS';
export const PROJECT_INFO_RECEIVE_ERROR = 'PROJECT_INFO_RECEIVE_ERROR';
