export const ADDING_GITLAB_PROJECT_START = 'ADDING_GITLAB_PROJECT_START';
export const ADDING_GITLAB_PROJECT_FAIL = 'ADDING_GITLAB_PROJECT_FAIL';
export const ADDING_GITLAB_PROJECT_SUCCESS = 'ADDING_GITLAB_PROJECT_SUCCESS';

export const GET_GITLAB_NAMESPACES_FAIL = 'GET_GITLAB_NAMESPACES_FAIL';
export const GET_GITLAB_NAMESPACES_SUCCESS = 'GET_GITLAB_NAMESPACES_SUCCESS';

export const CREATE_GITLAB_PROJECT_FAIL = 'CREATE_GITLAB_PROJECT_FAIL';
export const CREATE_GITLAB_PROJECT_SUCCESS = 'CREATE_GITLAB_PROJECT_SUCCESS';
