export const ADDING_GITLAB_PROJECT_START = 'ADDING_GITLAB_PROJECT_START';
export const ADDING_GITLAB_PROJECT_FAIL = 'ADDING_GITLAB_PROJECT_FAIL';
export const ADDING_GITLAB_PROJECT_SUCCESS = 'ADDING_GITLAB_PROJECT_SUCCESS';
