export const GOALS_RECEIVE_START = 'GOALS_RECEIVE_START';
export const GOALS_LIST_RECEIVE_SUCCESS = 'GOALS_LIST_RECEIVE_SUCCESS';
export const CLEAR_GOALS = 'CLEAR_GOALS';
export const CREATE_GOAL_START = 'CREATE_GOAL_START';
export const CREATE_GOAL = 'CREATE_GOAL';
export const CREATE_GOAL_ERROR = 'CREATE_GOAL_ERROR';
export const EDIT_GOAL_START = 'EDIT_GOAL_START';
export const EDIT__GOAL = 'EDIT__GOAL';
