export const JIRA_AUTHORIZE_START = 'JIRA_AUTHORIZE_START';
export const JIRA_AUTHORIZE_SUCCESS = 'JIRA_AUTHORIZE_SUCCESS';
export const JIRA_AUTHORIZE_ERROR = 'JIRA_AUTHORIZE_ERROR';

export const JIRA_CREATE_PROJECT_START = 'JIRA_CREATE_PROJECT_START';
export const JIRA_CREATE_PROJECT_SUCCESS = 'JIRA_CREATE_PROJECT_SUCCESS';
export const JIRA_CREATE_PROJECT_ERROR = 'JIRA_CREATE_PROJECT_ERROR';

export const GET_JIRA_PROJECTS_START = 'GET_JIRA_PROJECTS_START';
export const GET_JIRA_PROJECTS_SUCCESS = 'GET_JIRA_PROJECTS_SUCCESS';
export const GET_JIRA_PROJECTS_ERROR = 'GET_JIRA_PROJECTS_ERROR';
