export const JIRA_AUTHORIZE_START = 'JIRA_AUTHORIZE_START';
export const JIRA_AUTHORIZE_SUCCESS = 'JIRA_AUTHORIZE_SUCCESS';
export const JIRA_AUTHORIZE_ERROR = 'JIRA_AUTHORIZE_ERROR';

export const JIRA_CREATE_PROJECT_START = 'JIRA_CREATE_PROJECT_START';
export const JIRA_CREATE_PROJECT_SUCCESS = 'JIRA_CREATE_PROJECT_SUCCESS';
export const JIRA_CREATE_PROJECT_ERROR = 'JIRA_CREATE_PROJECT_ERROR';

export const GET_JIRA_PROJECTS_START = 'GET_JIRA_PROJECTS_START';
export const GET_JIRA_PROJECTS_SUCCESS = 'GET_JIRA_PROJECTS_SUCCESS';
export const GET_JIRA_PROJECTS_ERROR = 'GET_JIRA_PROJECTS_ERROR';

export const GET_SIMTRACK_USERS_BY_NAME_START = 'GET_SIMTRACK_USERS_BY_NAME_START';
export const GET_SIMTRACK_USERS_BY_NAME_SUCCESS = 'GET_SIMTRACK_USERS_BY_NAME_SUCCESS';
export const GET_SIMTRACK_USERS_BY_NAME_ERROR = 'GET_SIMTRACK_USERS_BY_NAME_ERROR';

export const SET_ASSOCIATION_START = 'SET_ASSOCIATION_START';
export const SET_ASSOCIATION_SUCCESS = 'SET_ASSOCIATION_SUCCESS';
export const SET_ASSOCIATION_ERROR = 'SET_ASSOCIATION_ERROR';

export const CREATE_BATCH_START = 'CREATE_BATCH_START';
export const CREATE_BATCH_SUCCESS = 'CREATE_BATCH_SUCCESS';
export const CREATE_BATCH_ERROR = 'CREATE_BATCH_ERROR';
