export const MILESTONE_CREATE_REQUEST = 'MILESTONE_CREATE_REQUEST';
export const MILESTONE_CREATE_SUCCESS = 'MILESTONE_CREATE_SUCCESS';
export const MILESTONE_CREATE_FAILURE = 'MILESTONE_CREATE_FAILURE';

export const MILESTONE_EDIT_REQUEST = 'MILESTONE_EDIT_REQUEST';
export const MILESTONE_EDIT_SUCCESS = 'MILESTONE_EDIT_SUCCESS';
export const MILESTONE_EDIT_FAILURE = 'MILESTONE_EDIT_FAILURE';
