export const LEFT_COLUMN_TASKS_RECEIVE_START = 'LEFT_COLUMN_TASKS_RECEIVE_START';
export const LEFT_COLUMN_TASKS_RECEIVE_SUCCESS = 'LEFT_COLUMN_TASKS_RECEIVE_SUCCESS';
export const LEFT_COLUMN_TASKS_RECEIVE_ERROR = 'LEFT_COLUMN_TASKS_RECEIVE_ERROR';

export const RIGHT_COLUMN_TASKS_RECEIVE_START = 'RIGHT_COLUMN_TASKS_RECEIVE_START';
export const RIGHT_COLUMN_TASKS_RECEIVE_SUCCESS = 'RIGHT_COLUMN_TASKS_RECEIVE_SUCCESS';
export const RIGHT_COLUMN_TASKS_RECEIVE_ERROR = 'RIGHT_COLUMN_TASKS_RECEIVE_ERROR';
