export const PORTFOLIO_RECEIVE_START = 'PORTFOLIO_RECEIVE_START';
export const PORTFOLIO_RECEIVE_SUCCESS = 'PORTFOLIO_RECEIVE_SUCCESS';
export const PORTFOLIO_NAME_RECEIVE_START = 'PORTFOLIO_NAME_RECEIVE_START';
export const PORTFOLIO_NAME_RECEIVE_SUCCESS = 'PORTFOLIO_NAME_RECEIVE_SUCCESS';
