export const PROJECT_INFO_RECEIVE_START = 'PROJECT_INFO_RECEIVE_START';
export const PROJECT_INFO_RECEIVE_SUCCESS = 'PROJECT_INFO_RECEIVE_SUCCESS';
export const PROJECT_INFO_RECEIVE_ERROR = 'PROJECT_INFO_RECEIVE_ERROR';

export const PROJECT_CHANGE_START = 'PROJECT_CHANGE_START';
export const PROJECT_CHANGE_SUCCESS = 'PROJECT_CHANGE_SUCCESS';

export const PROJECT_SPRINTS_CREATE_START = 'PROJECT_SPRINTS_CREATE_START';
export const PROJECT_SPRINTS_CREATE_SUCCESS = 'PROJECT_SPRINTS_CREATE_SUCCESS';
export const PROJECT_SPRINTS_CREATE_ERROR = 'PROJECT_SPRINTS_CREATE_ERROR';

export const EDIT_START = 'EDIT_START';
export const EDIT_FINISH = 'EDIT_FINISH';
