export const PROJECT_INFO_RECEIVE_START = 'PROJECT_INFO_RECEIVE_START';
export const PROJECT_INFO_RECEIVE_SUCCESS = 'PROJECT_INFO_RECEIVE_SUCCESS';

export const PROJECT_USERS_RECEIVE_START = 'PROJECT_USERS_RECEIVE_START';
export const PROJECT_USERS_RECEIVE_SUCCESS = 'PROJECT_USERS_RECEIVE_SUCCESS';

export const PROJECT_CHANGE_START = 'PROJECT_CHANGE_START';
export const PROJECT_CHANGE_SUCCESS = 'PROJECT_CHANGE_SUCCESS';

export const PROJECT_GET_USERS_START = 'PROJECT_GET_USERS_START';
export const PROJECT_GET_USERS_SUCCESS = 'PROJECT_GET_USERS_SUCCESS';

export const BIND_USER_TO_PROJECT_START = 'BIND_USER_TO_PROJECT_START';
export const BIND_USER_TO_PROJECT_SUCCESS = 'BIND_USER_TO_PROJECT_SUCCESS';

export const EDIT_START = 'EDIT_START';
export const EDIT_FINISH = 'EDIT_FINISH';

export const OPEN_CREATE_TASK_MODAL = 'OPEN_CREATE_TASK_MODAL';
export const CLOSE_CREATE_TASK_MODAL = 'CLOSE_CREATE_TASK_MODAL';

export const TASK_CREATE_REQUEST_START = 'TASK_CREATE_REQUEST_START';
export const TASK_CREATE_REQUEST_SUCCESS = 'TASK_CREATE_REQUEST_SUCCESS';
