export const PROJECT_INFO_RECEIVE_START = 'PROJECT_INFO_RECEIVE_START';
export const PROJECT_INFO_RECEIVE_SUCCESS = 'PROJECT_INFO_RECEIVE_SUCCESS';

export const PROJECT_CHANGE_START = 'PROJECT_CHANGE_START';
export const PROJECT_CHANGE_SUCCESS = 'PROJECT_CHANGE_SUCCESS';

export const EDIT_START = 'EDIT_START';
export const EDIT_FINISH = 'EDIT_FINISH';

export const OPEN_CREATE_TASK_MODAL = 'OPEN_CREATE_TASK_MODAL';
export const CLOSE_CREATE_TASK_MODAL = 'CLOSE_CREATE_TASK_MODAL';
