export const PROJECTS_RECEIVE_START = 'PROJECTS_RECEIVE_START';
export const PROJECTS_RECEIVE_SUCCESS = 'PROJECTS_RECEIVE_SUCCESS';

export const OPEN_CREATE_PROJECT_MODAL = 'OPEN_CREATE_PROJECT_MODAL';
export const CLOSE_CREATE_PROJECT_MODAL = 'CLOSE_CREATE_PROJECT_MODAL';

export const PROJECT_CREATE_START = 'PROJECT_CREATE_START';
export const PROJECT_CREATE_SUCCESS = 'PROJECT_CREATE_SUCCESS';
