export const SPRINTS_CREATE_START = 'SPRINTS_CREATE_START';
export const SPRINTS_CREATE_SUCCESS = 'SPRINTS_CREATE_SUCCESS';
export const SPRINTS_CREATE_ERROR = 'SPRINTS_CREATE_ERROR';

export const SPRINTS_DELETE_START = 'SPRINTS_DELETE_START';
export const SPRINTS_DELETE_SUCCESS = 'SPRINTS_DELETE_SUCCESS';
export const SPRINTS_DELETE_ERROR = 'SPRINTS_DELETE_ERROR';

export const SPRINTS_EDIT_START = 'SPRINTS_EDIT_START';
export const SPRINTS_EDIT_SUCCESS = 'SPRINTS_EDIT_SUCCESS';
export const SPRINTS_EDIT_ERROR = 'SPRINTS_EDIT_ERROR';

export const BACKLOG_ID = 0;
