export const TAGS_CREATE_START = 'TAGS_CREATE_START';
export const TAGS_CREATE_SUCCESS = 'TAGS_CREATE_SUCCESS';
export const TAGS_CREATE_ERROR = 'TAGS_CREATE_ERROR';
export const TAGS_DELETE_START = 'TAGS_DELETE_START';
export const TAGS_DELETE_SUCCESS = 'TAGS_DELETE_SUCCESS';
export const TAGS_DELETE_ERROR = 'TAGS_DELETE_ERROR';
