export const GET_TASK_REQUEST_SENT = 'GET_TASK_REQUEST_SENT';
export const GET_TASK_REQUEST_SUCCESS = 'GET_TASK_REQUEST_SUCCESS';

export const TASK_CHANGE_REQUEST_SENT = 'TASK_CHANGE_REQUEST_SENT';
export const TASK_CHANGE_REQUEST_SUCCESS = 'TASK_CHANGE_REQUEST_SUCCESS';

export const TASK_EDIT_START = 'TASK_EDIT_START';
export const TASK_EDIT_FINISH = 'TASK_EDIT_FINISH';
