export const GET_TASK_REQUEST_SENT = 'GET_TASK_REQUEST_SENT';
export const GET_TASK_REQUEST_SUCCESS = 'GET_TASK_REQUEST_SUCCESS';
export const GET_TASK_REQUEST_FAIL = 'GET_TASK_REQUEST_FAIL';

export const GET_TASK_HISTORY_REQUEST_SENT = 'GET_TASK_HISTORY_REQUEST_SENT';
export const GET_TASK_HISTORY_REQUEST_SUCCESS = 'GET_TASK_HISTORY_REQUEST_SUCCESS';

export const GET_TASK_SPENT_REQUEST_SENT = 'GET_TASK_SPENT_REQUEST_SENT';
export const GET_TASK_SPENT_REQUEST_SUCCESS = 'GET_TASK_SPENT_REQUEST_SUCCESS';

export const TASK_CHANGE_REQUEST_SENT = 'TASK_CHANGE_REQUEST_SENT';
export const TASK_CHANGE_REQUEST_SUCCESS = 'TASK_CHANGE_REQUEST_SUCCESS';
export const TASK_CHANGE_REQUEST_FAIL = 'TASK_CHANGE_REQUEST_FAIL';
export const ERROR_CLEAR = 'ERROR_CLEAR';

export const TASK_EDIT_START = 'TASK_EDIT_START';
export const TASK_EDIT_FINISH = 'TASK_EDIT_FINISH';

export const TASK_CHANGE_USER_SENT = 'TASK_CHANGE_USER_SENT';
export const TASK_CHANGE_USER_SUCCESS = 'TASK_CHANGE_USER_SUCCESS';

export const TASK_LINK_SENT = 'TASK_LINK_SENT';
export const TASK_LINK_SUCCESS = 'TASK_LINK_SUCCESS';

export const TASK_ATTACHMENT_REMOVE_FAIL = 'TASK_ATTACHMENT_REMOVE_FAIL';
export const TASK_ATTACHMENT_REMOVE_SUCCESS = 'TASK_ATTACHMENT_REMOVE_SUCCESS';
export const TASK_ATTACHMENT_REMOVE_REQUEST = 'TASK_ATTACHMENT_REMOVE_REQUEST';

export const TASK_ATTACHMENT_UPLOAD_REQUEST = 'TASK_ATTACHMENT_UPLOAD_REQUEST';
export const TASK_ATTACHMENT_UPLOAD_PROGRESS = 'TASK_ATTACHMENT_UPLOAD_PROGRESS';
export const TASK_ATTACHMENT_UPLOAD_SUCCESS = 'TASK_ATTACHMENT_UPLOAD_SUCCESS';
export const TASK_ATTACHMENT_UPLOAD_FAIL = 'TASK_ATTACHMENT_UPLOAD_FAIL';

export const GET_COMMENTS_BY_TASK_REQUEST = 'GET_COMMENTS_BY_TASK_REQUEST';
export const GET_COMMENTS_BY_TASK_SUCCESS = 'GET_COMMENTS_BY_TASK_SUCCESS';
export const GET_COMMENTS_BY_TASK_FAIL = 'GET_COMMENTS_BY_TASK_FAIL';

export const PUBLISH_COMMENT_REQUEST = 'PUBLISH_COMMENT_REQUEST';
export const PUBLISH_COMMENT_SUCCESS = 'PUBLISH_COMMENT_SUCCESS';
export const PUBLISH_COMMENT_FAIL = 'PUBLISH_COMMENT_FAIL';

export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST';
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_FAIL = 'REMOVE_COMMENT_FAIL';

export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
export const UPDATE_COMMENT_FAIL = 'UPDATE_COMMENT_FAIL';

export const SET_CURRENT_COMMENT_TEXT = 'SET_CURRENT_COMMENT_TEXT';
export const SELECT_COMMENT_FOR_REPLY = 'SELECT_COMMENT_FOR_REPLY';
export const SET_COMMENT_FOR_EDIT = 'SET_COMMENT_FOR_EDIT';
export const RESET_CURRENT_EDITING_COMMENT = 'RESET_CURRENT_EDITING_COMMENT';
export const SET_CURRENT_COMMENT_EXPIRED = 'SET_CURRENT_COMMENT_EXPIRED';
export const SET_HIGHLIGHTED_COMMENT = 'SET_HIGHLIGHTED_COMMENT';

export const CLEAR_CURRENT_TASK = 'CLEAR_CURRENT_TASK';

export const TASK_STATUS_DEVELOP_PLAY = 2;
export const TASK_STATUS_CLOSED = 10;
export const TASK_STATUS_DEVELOP_STOP = 3;
export const TASK_STATUS_CODE_REVIEW_PLAY = 4;
export const TASK_STATUS_CODE_REVIEW_STOP = 5;
export const TASK_STATUS_QA_STOP = 6;
export const TASK_STATUS_QA_PLAY = 7;
