export const TASKS_RECEIVE_START = 'TASKS_RECEIVE_START';
export const TASKS_RECEIVE_SUCCESS = 'TASKS_RECEIVE_SUCCESS';
export const TASKS_LIST_RECEIVE_SUCCESS = 'TASKS_LIST_RECEIVE_SUCCESS';
export const CLEAR_CURRENT_PROJECT_AND_TASKS = 'CLEAR_CURRENT_PROJECT_AND_TASKS';
