export const GET_ALL_TEST_PLANS_START = 'GET_ALL_TEST_PLANS_START';
export const GET_ALL_TEST_PLANS_SUCCESS = 'GET_ALL_TEST_PLANS_SUCCESS';

export const GET_TEST_PLAN_BY_ID_START = 'GET_TEST_PLAN_BY_ID_START';
export const GET_TEST_PLAN_BY_ID_SUCCESS = 'GET_TEST_PLAN_BY_ID_SUCCESS';

export const CREATE_TEST_PLAN_START = 'CREATE_TEST_PLAN_START';
export const CREATE_TEST_PLAN_SUCCESS = 'CREATE_TEST_PLAN_SUCCESS';

export const UPDATE_TEST_PLAN_START = 'UPDATE_TEST_PLAN_START';
export const UPDATE_TEST_PLAN_SUCCESS = 'UPDATE_TEST_PLAN_SUCCESS';

export const DELETE_TEST_PLAN_START = 'DELETE_TEST_PLAN_START';
export const DELETE_TEST_PLAN_SUCCESS = 'DELETE_TEST_PLAN_SUCCESS';

export default {
  GET_ALL_TEST_PLANS_START,
  GET_ALL_TEST_PLANS_SUCCESS,
  GET_TEST_PLAN_BY_ID_START,
  GET_TEST_PLAN_BY_ID_SUCCESS,
  CREATE_TEST_PLAN_START,
  CREATE_TEST_PLAN_SUCCESS,
  UPDATE_TEST_PLAN_START,
  UPDATE_TEST_PLAN_SUCCESS,
  DELETE_TEST_PLAN_START,
  DELETE_TEST_PLAN_SUCCESS
};
