export const GET_ALL_TEST_SUITES_START = 'GET_ALL_TEST_SUITES_START';
export const GET_ALL_TEST_SUITES_SUCCESS = 'GET_ALL_TEST_SUITES_SUCCESS';

export const GET_TEST_SUITES_REFERENCE_START = 'GET_TEST_SUITES_REFERENCE_START';
export const GET_TEST_SUITES_REFERENCE_SUCCESS = 'GET_TEST_SUITES_REFERENCE_SUCCESS';

export const GET_TEST_SUITE_BY_ID_START = 'GET_TEST_SUITE_BY_ID_START';
export const GET_TEST_SUITE_BY_ID_SUCCESS = 'GET_TEST_SUITE_BY_ID_SUCCESS';

export const CREATE_TEST_SUITE_START = 'CREATE_TEST_SUITE_START';
export const CREATE_TEST_SUITE_SUCCESS = 'CREATE_TEST_SUITE_SUCCESS';

export const COPY_TEST_SUITE_START = 'COPY_TEST_SUITE_START';
export const COPY_TEST_SUITE_SUCCESS = 'COPY_TEST_SUITE_SUCCESS';

export const UPDATE_TEST_SUITE_START = 'UPDATE_TEST_SUITE_START';
export const UPDATE_TEST_SUITE_SUCCESS = 'UPDATE_TEST_SUITE_SUCCESS';

export const DELETE_TEST_SUITE_START = 'DELETE_TEST_SUITE_START';
export const DELETE_TEST_SUITE_SUCCESS = 'DELETE_TEST_SUITE_SUCCESS';

export default {
  GET_ALL_TEST_SUITES_START,
  GET_ALL_TEST_SUITES_SUCCESS,
  GET_TEST_SUITES_REFERENCE_START,
  GET_TEST_SUITES_REFERENCE_SUCCESS,
  GET_TEST_SUITE_BY_ID_START,
  GET_TEST_SUITE_BY_ID_SUCCESS,
  CREATE_TEST_SUITE_START,
  CREATE_TEST_SUITE_SUCCESS,
  COPY_TEST_SUITE_START,
  COPY_TEST_SUITE_SUCCESS,
  UPDATE_TEST_SUITE_START,
  UPDATE_TEST_SUITE_SUCCESS,
  DELETE_TEST_SUITE_START,
  DELETE_TEST_SUITE_SUCCESS
};
