export const GET_ALL_TEST_CASES_START = 'GET_ALL_TEST_CASES_START';
export const GET_ALL_TEST_CASES_SUCCESS = 'GET_ALL_TEST_CASES_SUCCESS';

export const GET_TEST_CASE_BY_ID_START = 'GET_TEST_CASE_BY_ID_START';
export const GET_TEST_CASE_BY_ID_SUCCESS = 'GET_TEST_CASE_BY_ID_SUCCESS';

export const CREATE_TEST_CASE_START = 'CREATE_TEST_CASE_START';
export const CREATE_TEST_CASE_SUCCESS = 'CREATE_TEST_CASE_SUCCESS';

export const UPDATE_TEST_CASE_START = 'UPDATE_TEST_CASE_START';
export const UPDATE_TEST_CASE_SUCCESS = 'UPDATE_TEST_CASE_SUCCESS';

export const DELETE_TEST_CASE_START = 'DELETE_TEST_CASE_START';
export const DELETE_TEST_CASE_SUCCESS = 'DELETE_TEST_CASE_SUCCESS';

export default {
  GET_ALL_TEST_CASES_START,
  GET_ALL_TEST_CASES_SUCCESS,
  GET_TEST_CASE_BY_ID_START,
  GET_TEST_CASE_BY_ID_SUCCESS,
  CREATE_TEST_CASE_START,
  CREATE_TEST_CASE_SUCCESS,
  UPDATE_TEST_CASE_START,
  UPDATE_TEST_CASE_SUCCESS,
  DELETE_TEST_CASE_START,
  DELETE_TEST_CASE_SUCCESS
};
