export const TIMESHEET_PLAYER_RECEIVE_START = 'TIMESHEET_PLAYER_RECEIVE_START';
export const TIMESHEET_PLAYER_RECEIVE_SUCCESS = 'TIMESHEET_PLAYER_RECEIVE_SUCCESS';
export const TIMESHEET_PLAYER_RECEIVE_FAIL = 'TIMESHEET_PLAYER_RECEIVE_FAIL';
export const TIMESHEET_PLAYER_UPDATE_RECEIVE_SUCCESS = 'TIMESHEET_PLAYER_UPDATE_RECEIVE_SUCCESS';
export const TIMESHEET_PLAYER_TIMESHEET_UPDATE_RECEIVE_SUCCESS = 'TIMESHEET_PLAYER_TIMESHEET_UPDATE_RECEIVE_SUCCESS';
export const GET_ACTIVE_TASK = 'GET_ACTIVE_TASK'
