export const GET_TIMESHEETS_START = 'GET_TIMESHEETS_START';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';

export const SET_WEEK = 'SET_WEEK';
