export const GET_TIMESHEETS_START = 'GET_TIMESHEETS_START';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';

export const GET_AVERAGE_NUMBER_OF_EMPLOYEES_START = 'GET_AVERAGE_NUMBER_OF_EMPLOYEES_START';
export const GET_AVERAGE_NUMBER_OF_EMPLOYEES_SUCCESS = 'GET_AVERAGE_NUMBER_OF_EMPLOYEES_SUCCESS';
export const GET_AVERAGE_NUMBER_OF_EMPLOYEES_ERROR = 'GET_AVERAGE_NUMBER_OF_EMPLOYEES_ERROR';

export const SUBMIT_TIMESHEETS_START = 'SUBMIT_TIMESHEETS_START';
export const SUBMIT_TIMESHEETS_SUCCESS = 'SUBMIT_TIMESHEETS_SUCCESS';
export const SUBMIT_TIMESHEETS_ERROR = 'SUBMIT_TIMESHEETS_ERROR';

export const APPROVE_TIMESHEETS_START = 'APPROVE_TIMESHEETS_START';
export const APPROVE_TIMESHEETS_SUCCESS = 'APPROVE_TIMESHEETS_SUCCESS';
export const APPROVE_TIMESHEETS_ERROR = 'APPROVE_TIMESHEETS_ERROR';

export const REJECT_TIMESHEETS_START = 'REJECT_TIMESHEETS_START';
export const REJECT_TIMESHEETS_SUCCESS = 'REJECT_TIMESHEETS_SUCCESS';
export const REJECT_TIMESHEETS_ERROR = 'REJECT_TIMESHEETS_ERROR';

export const GET_COMPANY_TIMESHEETS_START = 'GET_COMPANY_TIMESHEETS_START';
export const GET_COMPANY_TIMESHEETS_SUCCESS = 'GET_COMPANY_TIMESHEETS_SUCCESS';
export const GET_COMPANY_TIMESHEETS_ERROR = 'GET_COMPANY_TIMESHEETS_ERROR';

export const CREATE_TIMESHEET_START = 'CREATE_TIMESHEET_START';
export const CREATE_TIMESHEET_SUCCESS = 'CREATE_TIMESHEET_SUCCESS';
export const CREATE_TIMESHEET_ERROR = 'CREATE_TIMESHEET_ERROR';

export const UPDATE_TIMESHEET_START = 'UPDATE_TIMESHEET_START';
export const UPDATE_TIMESHEET_SUCCESS = 'UPDATE_TIMESHEET_SUCCESS';

export const DELETE_TIMESHEET_START = 'DELETE_TIMESHEET_START';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
export const DELETE_TEMP_TIMESHEET = 'DELETE_TEMP_TIMESHEET';
export const EDIT_TEMP_TIMESHEET = 'EDIT_TEMP_TIMESHEET';

export const SET_WEEK = 'SET_WEEK';
export const CHANGE_TASK = 'CHANGE_TASK';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const CHANGE_ACTIVITY_TYPE = 'CHANGE_ACTIVITY_TYPE';
export const CLEAR_MODAL_STATE = 'CLEAR_MODAL_STATE';
export const FILTER_TASKS = 'FILTER_TASKS';
export const FILTER_PROJECTS = 'FILTER_PROJECTS';

export const ADD_ACTIVITY = 'ADD_ACTIVITY';

export const CLEAR_TIMESHEETS_STATE = 'CLEAR_TIMESHEETS_STATE';

export const TIMESHEET_STATUS_FILLED = 1;
export const TIMESHEET_STATUS_REJECTED = 2;
export const TIMESHEET_STATUS_SUBMITTED = 3;
export const TIMESHEET_STATUS_APPROVED = 4;
