export const GET_TIMESHEETS_START = 'GET_TIMESHEETS_START';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';

export const CREATE_TIMESHEET_START = 'CREATE_TIMESHEET_START';
export const CREATE_TIMESHEET_SUCCESS = 'CREATE_TIMESHEET_SUCCESS';

export const UPDATE_TIMESHEET_START = 'UPDATE_TIMESHEET_START';
export const UPDATE_TIMESHEET_SUCCESS = 'UPDATE_TIMESHEET_SUCCESS';

export const DELETE_TIMESHEET_START = 'DELETE_TIMESHEET_START';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';

export const SET_WEEK = 'SET_WEEK';
export const CHANGE_TASK = 'CHANGE_TASK';
export const CHANGE_PROJECT = 'CHANGE_PROJECT';
export const CHANGE_ACTIVITY_TYPE = 'CHANGE_ACTIVITY_TYPE';
export const CLEAR_MODAL_STATE = 'CLEAR_MODAL_STATE';
export const FILTER_TASKS = 'FILTER_TASKS';
