export const USER_INFO_RECEIVE_START = 'USER_INFO_RECEIVE_START';
export const USER_INFO_RECEIVE_SUCCESS = 'USER_INFO_RECEIVE_SUCCESS';
export const USER_INFO_RECEIVE_ERROR = 'USER_INFO_RECEIVE_ERROR';
