export const GET_DEV_OPS_USERS_START = 'GET_DEV_OPS_USERS_START';
export const GET_DEV_OPS_USERS_SUCCESS = 'GET_DEV_OPS_USERS_SUCCESS';
export const GET_ALL_USERS_START = 'GET_ALL_USERS_START';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';

export const GET_USER_STATUS_START = 'GET_USER_STATUS_START';
export const GET_USER_STATUS_SUCCESS = 'GET_USER_STATUS_SUCCESS';

export const PURGE_USER = 'PURGE_USER';
