/**
 * Created by ira on 25.02.16.
 */

export default () => [
  {
    '_id': 5325,
    '_type': 'feature',
    'planned_time': 1.5,
    'current_time': 0,
    'gain_time': 3,
    'priority': 4,
    'name': 'Elit laboris',
    'status': 'On Track',
    'complete': 42,
    'owner': 'Leo.Harris',
    'creator': 'Theo.Ondricka',
    'begin_date': '3/6/1972',
    'plan_end_date': '7/17/1972',
    'fact_end_date': '11/17/1993',
    'update_date': '10/24/1955',
    'id_proj': '1'
  },
  {
    '_id': 1081,
    '_type': 'task',
    'planned_time': 6,
    'current_time': 0,
    'gain_time': 3,
    'priority': 2,
    'name': 'Culpa in',
    'status': 'Proposed',
    'complete': 16,
    'owner': 'Boyd.Bode',
    'creator': 'Eugene.Abshire',
    'begin_date': '1/10/1959',
    'plan_end_date': '9/19/1951',
    'fact_end_date': '4/12/1979',
    'update_date': '3/10/1985',
    'id_proj': '2'
  },
  {
    '_id': 3070,
    '_type': 'bug',
    'planned_time': 4.5,
    'current_time': 3,
    'gain_time': 3,
    'priority': 3,
    'name': 'Occaecat',
    'status': 'Off Track',
    'complete': 6,
    'owner': 'Tina.Murphy',
    'creator': 'Aiyana.Berge',
    'begin_date': '5/22/1952',
    'plan_end_date': '12/7/1985',
    'fact_end_date': '6/11/1989',
    'update_date': '10/5/1983',
    'id_proj': '1'
  },
  {
    '_id': 5071,
    '_type': 'task',
    'planned_time': 3,
    'current_time': 0,
    'gain_time': 4.5,
    'priority': 3,
    'name': 'Exercitation est lorem ipsum',
    'status': 'On Track',
    'complete': 70,
    'owner': 'Laurel.Boehm',
    'creator': 'Carolyne.Lehner',
    'begin_date': '7/6/1975',
    'plan_end_date': '8/28/1994',
    'fact_end_date': '9/19/1964',
    'update_date': '11/24/1966',
    'id_proj': '1'
}];
